apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: be-pv-claim
  namespace: blog-prod
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi