apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: be
  namespace: blog-prod
spec:
  serviceName: be-service
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: be
          image:  ghcr.io/viki123v/blog-sys-cicd/be:2.0.1
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: be-pv
              mountPath: /app/src/assets
          env:
            - name: JWK
              valueFrom:
                secretKeyRef:
                  name: be-secret 
                  key: JWK
            - name: ALLOWED_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: be-secret
                  key: ALLOWED_ORIGIN
            - name: OBJECT_URL
              value: http://be-service.blog-prod.svc.cluster.local
            - name: DB_PORT
              value: '5432'
            - name: DB_HOST
              value: blog-dbs.blog-prod
            - name: POSTGRES_DB
              value: blog
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: viki.blog-dbs.credentials.postgresql.acid.zalan.do
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: viki.blog-dbs.credentials.postgresql.acid.zalan.do
                  key: password
      volumes:
        - name: be-pv
          persistentVolumeClaim:
            claimName: be-pv-claim
