# Project maybe will have to change 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/viki123v/blog-sys-cicd
    path: infra/deployments
    targetRevision: master
    directory:
      recurse: true
      jsonnet: {}
      include: infra/deployments/argo/app.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
