apiVersion: v1
kind: Service
metadata:
  name: postgres-operator
  namespace: blog-prod 
spec:
  type: ClusterIP
  ports:
  - port: 5432 
    protocol: TCP
    targetPort: 8080
  selector:
    name: postgres-operator