apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: be-pv-claim
  namespace: blog-prod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi