apiVersion: v1
kind: PersistentVolume
metadata:
  name: be-pv 
  labels:
    type: local
  namespace: blog-prod
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/k3dvol"
