apiVersion: v1
kind: PersistentVolume
metadata:
  name: be-pv 
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/k3dvol"
